### ISSUE TITLE
 question about hbond between ligand and solvent (water)

### ISSUE THREAD

**Issue by yousefymohammad** [djmaity/md-davis#8]
* MD DaVis version:
* Python version:
* Operating System:

### Description

I want to calculate the hydrogen bond interaction between ligand and solvent. at the end it does not show any interaction between ligand and water. However, when I am using the command "gmx hbond -s md.tpr -f md.xtc -num ligan_water", it shows me averagely 4-6 hbond interaction between pairs atoms. could you please explain what is happening and what is the solution. 
 

### What I Did

I am doing the normal procedure based on the instruction
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by djmaity** [comment]
I followed the [lysozyme in water tutorial](http://www.mdtutorials.com/gmx/lysozyme/) to obtain an example trajectory to test. Then, I used the following command to calculate the hydrogen bonds between the protein and the solvent.
```
gmx hbond -f md_0_1.xtc -s md_0_1.tpr -num hbnum.xvg -hbm hb_matrix -hbn hb_index
```
I selected the groups 'Protein' and  'SOL' when prompted. If your ligand and solvent are in different groups, please select them accordingly. I obtained a PDB file containing the entire system with:
```
gmx trjconv -f md_0_1.xtc -s md_0_1.tpr -o md_0_1_for_hbond.pdb -dump 0
```
I selected the group 'System' when prompted. Next, I used the following `md-davis` command to generate the hydrogen bond data:
```
md-davis hbond -x hb_matrix.xpm -i hb_index.ndx -s md_0_1_for_hbond.pdb --save_pickle hb_data.p -g hbonds_Protein-SOL
```
Since I had selected 'Protein' and  'SOL' in the `gmx hbond` command. The last group in the **hb_index.ndx** file was `hbonds_Protein-SOL` as shown below:
```
33812  33815  33818  33821  33824  33827  33830  33833  33836  33839  33842  33845  33848  33851  33854
 33857  33860  33863  33866
[ hbonds_Protein-SOL ]
      1     -1   8243
      1     -1  11567
```
Therefore, `hbonds_Protein-SOL` was passed to the `-g` option. If your selected groups are different, please check the **hb_index.ndx** file and change the `-g` option accordingly.

Finally, I created the attached plot with the following:
```
md-davis plot_hbond --percent --total_frames 101 --cutoff 33 -o hbond_matrix.html hb_data.p
```
Please try the step above and let me know if it resolves your issue.

Interestingly, the index of all the donor hydrogens in my **hb_index.ndx** file was **-1**. I suspect this is a nuance of the GROMACS version I used. This did not affect the plot below since only the donor and acceptor atoms are listed. However, the information about which of the two hydrogens in a water molecule forms the hydrogen bond with the protein is lost.

Also, note that the residue index in a PDB file is limited to 9999. Hence, the labels for solvent molecules in the plot below are not unique.

![lysozyme_water_hbonds](https://github.com/djmaity/md-davis/assets/13766712/3e70975e-9c44-4166-8f54-df9fbb0dde65)
